@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Apr 13 20:05:47 +0530 2025
REM SW Build 5266912 on Sun Dec 15 09:03:24 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim traffic_controller_behav -key {Behavioral:sim_1:Functional:traffic_controller} -tclbatch traffic_controller.tcl -log simulate.log"
call xsim  traffic_controller_behav -key {Behavioral:sim_1:Functional:traffic_controller} -tclbatch traffic_controller.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
