@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 21 01:01:08 +0530 2025
REM SW Build 5266912 on Sun Dec 15 09:03:24 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim _4to1MUX_behav -key {Behavioral:sim_1:Functional:_4to1MUX} -tclbatch _4to1MUX.tcl -log simulate.log"
call xsim  _4to1MUX_behav -key {Behavioral:sim_1:Functional:_4to1MUX} -tclbatch _4to1MUX.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
